### PR TITLE
Added auth example with Bearer Token

### PR DESCRIPTION
**Pull request by keyuls**
chai-http supports Authorization with Bearer Token. But, this feature is not mentioned anywhere on the site or readme file. 
This would be useful for many developers & Tester.

Ref: https://github.com/chaijs/chai-http/blob/master/dist/chai-http.js#L3359

### CODE REVIEW

**Review by austince — APPROVED** [review]
Hey @keyuls, this looks good to me, thanks! I'll merge this sometime this week when I try to merge + release #281 as well.

**Comment by austince** [comment]
Update: will merge it right after #283 so we have something to test the CI fix with.

**Comment by keyuls** [comment]
Thanks @austince 

Do you know when will this change reflect on https://www.chaijs.com/plugins/chai-http/ page?

**Comment by austince** [comment]
I'm actually not sure how that homepage is updated -- @keithamus will know.

**Comment by keithamus** [comment]
Should be updated nightly.

**Pull request merged**
