### PR TITLE
4.2.1

### PR DESCRIPTION
**Pull request by austince**
Chore commit for version 4.2.1

Fixes:
* https://github.com/chaijs/chai-http/pull/230

### CODE REVIEW

**Comment by vieiralucas** [comment]
@austince I believe you need to push a tag so travis deploys to npm.
Can you do that?

**Comment by austince** [comment]
Sure, I can draft a new release soon. Thanks for the review + merge!

**Comment by austince** [comment]
@keithamus @JamesMessinger, since you guys usually do the releasing, do you mind just giving a quick 'ok' before I go ahead and publish a GH release?

**Comment by JamesMessinger** [comment]
How does the "build" script in [package.json](https://github.com/chaijs/chai-http/blob/master/package.json) get run?  I don't see it being called in the [CI script](https://github.com/chaijs/chai-http/blob/master/.travis.yml), so does it have to be run manually and committed as part of this PR?

As far as I can tell, the CI script will just deploy whatever is checked into git.  And looking at the last-modified dates of the files, it seems like the build script hasn't been run in at least 4 months.

**Comment by vieiralucas** [comment]
My understanding is that it will run for commits that are tags.

**Comment by JamesMessinger** [comment]
Right, the deploy script will run for tagged commits.  But all the deploy script does is run `npm publish`.  It doesn't run `npm run build` first, so the `npm publish` command will simply publish whatever's in git.

@keithamus - Or am I missing something?

**Comment by keithamus** [comment]
@JamesMessinger you're correct - all that happens is tagged commits get `npm publish` run on them

Typically the release cycle starts by running `npm run build` and submitting a pull request with that. Usually that means `dist/chai-https.js` will change, however in this case the only changes made between `4.2.0` and this PR were to package.json, so the diff is pretty sparse.

I've gone and made https://github.com/chaijs/chai-http/releases/tag/4.2.1 which should get deployed shortly.

**Comment by keithamus** [comment]
I've run `npm run build` locally, and there are some minor changes to the README, and to the sourcemap in `dist/chai-http.min.js.map`. These look like changes we actually dont want to publish. I'll get around to fixing them soon, but my focus is on other parts of chai right now.

**Comment by austince** [comment]
Perhaps we could use something like [semantic-release](https://github.com/semantic-release/semantic-release) to save some of Keith's time?

**Pull request merged**
