### PR TITLE
4.3.0

### PR DESCRIPTION
**Pull request by austince**
Chore commit to release 4.3.0

Features:
- https://github.com/chaijs/chai-http/pull/243 (@mikemfleming)

### CODE REVIEW

**Comment by austince** [comment]
:balloon: do you want me to write up the release notes?

**Comment by austince** [comment]
Hey @keithamus, just looping back in if you have some time.

**Comment by keithamus** [comment]
We should enable semantic release, for sure! I don't have much time right now sadly, so I wont be able to spend any time on doing this, but I'm happy to glance over some PRs if you plan to make any ;)

**Comment by keithamus** [comment]
I've added release notes (https://github.com/chaijs/chai-http/releases/tag/4.3.0). The Travis build should deploy a new version when it passes: https://travis-ci.org/chaijs/chai-http/builds/524975518?utm_source=github_status&utm_medium=notification

**Comment by austince** [comment]
Awesome, thank you! I'll see if I can squeeze in a PR sometime soon :slightly_smiling_face:

**Comment by mikemfleming** [comment]
I'm happy to help out if there are any other issues y'all would like a contributor on. Is the help wanted label still viable? looks like it's got some old issues.

**Comment by keithamus** [comment]
@mikemfleming we're always happy to have contributors to anything in the chai ecosystem 😄. My latest efforts have been in refactoring our inspection engine (https://github.com/chaijs/loupe/pull/14) - it would be great to get some more tests written up for more complex use-cases (see https://github.com/chaijs/loupe/issues/13#issuecomment-450829328). Otherwise you could have a look through any issue on chai-http (https://github.com/chaijs/chai-http/issues) and help triage them 😄

**Pull request merged**
