### PR TITLE
build(travis): update npm token

### PR DESCRIPTION
**Pull request by keithamus**
/cc @austince @BigstickCarpet

### CODE REVIEW

**Comment by austince** [comment]
Awesome, thank you!

**Comment by keithamus** [comment]
@austince want to merge this one? 😜

**Comment by BigstickCarpet** [comment]
@austince - You can do it! You have the **power** now! 😄

**Comment by austince** [comment]
:smile: I would love to! Github doesn't believe I have the power though .. :cry:

**Comment by keithamus** [comment]
@austince You should have an org invite in your mailbox! Otherwise you can head to https://github.com/orgs/chaijs/invitation and you should be able to see it!

**Comment by keithamus** [comment]
Wooo 🎉🎉🎉

**Pull request merged**
