### PR TITLE
Fix for issue #254, add extended request method explanations to the README

### PR DESCRIPTION
**Pull request by theodorewahle**

### CODE REVIEW

**Comment by austince** [comment]
This looks great! @theodorewahle, could you just edit your commit message to something like `docs: add extended request method explanations` and then force push up? 

```shell
git commit --amend # change the message
git push --force # assuming your branch is set as upstream
```

**Comment by keithamus** [comment]
@austince just FYI we can use "squash and merge" to alter commits in these situations, rather than burden contributors with our commit style.

**Comment by austince** [comment]
@keithamus, I'm game for that - should we remove the **validate-commit-msg** status check then?

**Comment by keithamus** [comment]
@austince the `validate-commit-msg` check is not a required check, and so you're able to merge without it passing. I've kept it specifically not-required to allow for that scenario.

**Pull request merged**
