### PR TITLE
Changed .field to use .send instead.

### PR DESCRIPTION
**Pull request by BenAychh**
instead of
.field('foo', 'bar')

It should be saying
.send({foo: 'bar'})

### CODE REVIEW

**Comment by BenAychh** [comment]
Issue #86

**Comment by meeber** [comment]
Thank you for the PR @BenAychh!

I just reviewed #86 and I think there might be something else going on here.

According to the [SuperAgent documentation](https://visionmedia.github.io/superagent/#multipart-requests), `.field()` is for use with multipart requests.

I believe the POST variables are still being sent when `.field()` is used, they just aren't accessible in the `res` object in the same way as when they are sent via `.send()`.

I just ran a quick test using a [multipart-aware HTTP Post Dumping Service](http://posttestserver.com/), and it detected the POST variable that I set via `.field`. I didn't pursue how to locate that in the `res` object, but I suspect it's possible. At the very least, I observed the `multipart/form-data`'s `Content-Length` increasing as I added more fields.

```js
it("test", function (done) {
  chai.request("http://posttestserver.com/post.php")
    .post("")
    .field("APPLES", "BANANAS")
    .end(function (err, res) {
      console.log(res);
      done();
    });
});
```

Therefore, I think the documentation should instead be updated to indicate that `.field` is for multipart requests.

Also, `README.md` is generated via a build script, so any documentation changes should actually take place in [request.js](https://github.com/chaijs/chai-http/blob/master/lib/request.js).

@Doogiemuc @C00bra @keithamus Does this sound like a fair plan?

**Comment by Doogiemuc** [comment]
Sounds perfectly fine for me. Thank you for the deep and thorough analysis.  I vote for merging your pull request. *happy*

**Comment by barraponto** [comment]
I believe using `.send` defaults to sending a JSON encoded request body. If you want to form-encode, you have to explicitly `.type('form')`. Like this:

```javascript
chai.request(app).post('/user/login').type('form').send({username, email})
```

**Comment by wzup** [comment]
@barraponto 
How do you know about `.type('form')`? There is nothing said about it in docs of this so called "plugin".

Because what you say actually does work:
```
.type('form')
.send({foo: 'bar'})
```
Thanks, @barraponto. 
And no thanks to authors of the plugin.

**Comment by meeber** [comment]
@wzup I suspect he looked at the [superagent](https://github.com/visionmedia/superagent) documentation which is the underlying module powering chai-http. There are doubtlessly problems in this plugin's documentation; the creator hasn't been active in 4+ years. The documentation may have been correct that long ago. This plugin is 100% maintained by the community. If you wish to make it better and keep it current, please open a PR with corrections.

**Comment by barraponto** [comment]
Should we update the PR to include `type('form')`?

**Comment by keithamus** [comment]
Thanks for your work here @BenAychh and @barraponto 👏

**Comment by fedeolto** [comment]
@barraponto thank you so much for pointing out `type('form)` 🙏🏻

**Pull request closed without merging**
