### PR TITLE
chore: Add badges to the README.md

### PR DESCRIPTION
**Pull request by kiki1607**
Hello, 
I update the README.md with adding the NPM badge, the Dependencies badge and the DevDependecies badge. I Hope to have helped you a little bit.

### CODE REVIEW

**Comment by kiki1607** [comment]
I will reopen the pull request after fixing the problem of the commit name. Sorry for the disturb.

**Comment by kiki1607** [comment]
I'm sorry, but I don't get how to fix this problem... Can you help me? It would help me a lot in the future!

**Comment by austince** [comment]
Hi @kiki1607, thanks for the PR! I think this is a good addition but let's get some feedback from other members.

As for the commit message, the easiest way would be to edit your commit locally and then force push this branch.

```sh
git commit --amend # then change the message to something like: 'docs: add badges to the README'
git push --force # if you've set your branch as upstream
```

**Comment by vieiralucas** [comment]
Thanks @kiki1607, I agree that this is a great addition too.

@kiki1607 can you follow @austince advice and update the commit message?
Please feel free to ask if you need any further help.

**Pull request closed without merging**
