### PR TITLE
4.2.0

### PR DESCRIPTION
**Pull request by austince**
Chore commit for version 4.2.0.

Changes included:
- https://github.com/chaijs/chai-http/pull/221

Fixes:
- https://github.com/chaijs/chai-http/issues/209

### CODE REVIEW

**Comment by keithamus** [comment]
Someone else from @chaijs/chai-http should merge this and publish the release info!

**Comment by BigstickCarpet** [comment]
Done and [done](https://github.com/chaijs/chai-http/releases)

**Comment by austince** [comment]
Thanks @keithamus + @BigstickCarpet ! Would it be possible to publish to npm as well?

**Comment by BigstickCarpet** [comment]
@austince - It _should_ have published to npm automatically as part of the Travis CI script.  But [it failed due to an authentication error](https://travis-ci.org/chaijs/chai-http/jobs/422011486#L1599-L1611).

@keithamus - Looks like maybe you need to update [the encrypted npm credentials in the `.travis.yml` file](https://github.com/chaijs/chai-http/blob/master/.travis.yml#L10-L13)

**Comment by keithamus** [comment]
`4.1.0` and `4.2.0` are now published. I'll PR the token soon

**Pull request merged**
