### PR TITLE
use sentinal value to check cookies with domains

### LINKED ISSUE #43: expect cookie fails with a proper set-cookie header
In a test I'm making some expectations on the response. One of the expectations verifies the existence of a cookie in the form:

<pre>
expect(res).to.have.cookie('cookieName');
</pre>

The expectation fails while the response object contains the set-cookie header with the cookie.

Using v1.0.0

### PR DESCRIPTION
**Pull request by leggsimon**
Fixes #43

### CODE REVIEW

**Comment by keithamus** [comment]
Excellent. This looks great to me (LGTM)! @meeber @lucasfcosta @vieiralucas to corroborate.

**Comment by vieiralucas** [comment]
This LGTM, but I'm not in the [MAINTAINERS](https://github.com/chaijs/chai-http/blob/master/MAINTAINERS) file 😸

**Comment by keithamus** [comment]
Feel free to send a PR adding yourself!

**Comment by vieiralucas** [comment]
Here we go
LGTM

**Comment by leggsimon** [comment]
Thanks @vieiralucas

**Comment by MeenaAlfons** [comment]
When will this change get to some release?

**Pull request merged**
